### ISSUE TITLE
Discussion: package organization

### ISSUE THREAD

**Issue by jamestwebber** [MethodsDev/Mas-Seq-Magic-Pocket#3]
This issue is just to have a place to plan out some code organization. We want everything to be installable for reuse, which means python packaging.

After thinking about it a little bit I think it'd be nice to create a [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/) named `mdl` and everything gets installed under that namespace. So for instance this package could be `mdl.masseqviz` and we could write some future package `mdl.foo` and maintain it in a separate repo.

I can open a PR for this, but the basics are something like the following structure. It's a little complicated to set up at first but it keeps things clean and easier to maintain in the long term.

```
- src/
  - mdl/
    - masseqviz/  # code is all under here
      - __init__.py
      - ...
- tests/  # we should write tests eventually
  - ...  
- README.md
- LICENSE
- requirements.txt
- dev-requirements.txt
- pyproject.toml  # configures setuptools and various dev tools
- .pre-commit-config.yaml  # for running pre-commit hooks
```

[`pre-commit`](https://pre-commit.com/) is a tool for running code checks before committing to the repo. I like to use [`black`](https://black.readthedocs.io/en/stable/), [`isort`](https://pycqa.github.io/isort/), and [`flake8`](https://flake8.pycqa.org/en/latest/) to keep everything consistent and readable, and also minimize formatting issues in PRs.

**Comment by jamestwebber** [comment]
I'll just tag everyone who might have an opinion: @yueyaog @jonn-smith @kvg @viq854 @brianjohnhaas @GeorgescuC

**Comment by brianjohnhaas** [comment]
This looks great. I like the idea of separate repos where there are largely disjoint systems with distinct requirements.  We definitely wouldn't want to grow a single mega-package (dare I say like gatk... ) when we can keep certain parts nicely isolated.

**Comment by jamestwebber** [comment]
I will admit that I partially just want to figure out how to do it this way.

**Comment by jamestwebber** [comment]
Done in #4
